name: Test

on:
  pull_request:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run build
      - run: rm -rf node_modules
      - uses: ./
        with:
          file: clover.example.base.xml
      - uses: ./
        with:
          file: genotool.xml
          files: /var/www/html/app/Models/DawiLogger.php,/var/www/html/app/Models/DeletedUser.php